In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('admission.csv', sep = ';')

In [3]:
X = df.iloc[:, :-1].values # Todos os valores menos a ultima coluna
y = df.iloc[:,-1].values # Todos os valores a partir da ultima coluna

In [4]:
display(X)
display(y)

array([['Lucas', 337, 118, 4, 4.5, 4.5, 9.65, 1],
       ['Ana', 324, 107, 4, 4.0, 4.5, 8.87, 1],
       ['Jose', 316, 104, 3, 3.0, 3.5, 8.0, 1],
       ['Carlos', 322, 110, 3, 3.5, 2.5, 8.67, 1],
       ['Zileide', 314, 103, 2, 2.0, 3.0, 8.21, 0],
       ['Joana', 330, 115, 5, 4.5, 3.0, 9.34, 1],
       ['Davi', 321, 109, 3, 3.0, 4.0, 8.2, 1],
       ['Daniel', 308, 101, 2, 3.0, 4.0, 7.9, 0],
       ['Marcelo', 302, 102, 1, 2.0, 1.5, 8.0, 0]], dtype=object)

array([1, 1, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [5]:
from sklearn.impute import SimpleImputer

In [6]:
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imputer.fit_transform(X[:,1:])

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
lb_X = LabelEncoder()

In [9]:
X[:,0] = lb_X.fit_transform(X[:, 0])

In [10]:
print(X)

[[6 337 118 4 4.5 4.5 9.65 1]
 [0 324 107 4 4.0 4.5 8.87 1]
 [5 316 104 3 3.0 3.5 8.0 1]
 [1 322 110 3 3.5 2.5 8.67 1]
 [8 314 103 2 2.0 3.0 8.21 0]
 [4 330 115 5 4.5 3.0 9.34 1]
 [3 321 109 3 3.0 4.0 8.2 1]
 [2 308 101 2 3.0 4.0 7.9 0]
 [7 302 102 1 2.0 1.5 8.0 0]]


In [11]:
X = X[:, 1:] # A partir da coluna 2

In [12]:
D = pd.get_dummies(X[:, 0]) # Cria variaveis binarias para valores qualitativos

In [13]:
X = np.insert(X, 0, D.values, axis= 1) # Insere esses valores de forma colunar no index 0

In [15]:
print(X)

[[False False False False False False False False True 337 118 4 4.5 4.5
  9.65 1]
 [False False False False False False False True False 324 107 4 4.0 4.5
  8.87 1]
 [False False False False True False False False False 316 104 3 3.0 3.5
  8.0 1]
 [False False True False False False False False False 322 110 3 3.5 2.5
  8.67 1]
 [False False False False False False True False False 314 103 2 2.0 3.0
  8.21 0]
 [False False False True False False False False False 330 115 5 4.5 3.0
  9.34 1]
 [False True False False False False False False False 321 109 3 3.0 4.0
  8.2 1]
 [False False False False False True False False False 308 101 2 3.0 4.0
  7.9 0]
 [True False False False False False False False False 302 102 1 2.0 1.5
  8.0 0]]


In [16]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state= 45) # Divide o df em treino e teste

In [21]:
print(X_train)

[[False False False False False False False True False 324 107 4 4.0 4.5
  8.87 1]
 [False True False False False False False False False 321 109 3 3.0 4.0
  8.2 1]
 [True False False False False False False False False 302 102 1 2.0 1.5
  8.0 0]
 [False False False True False False False False False 330 115 5 4.5 3.0
  9.34 1]
 [False False False False False False False False True 337 118 4 4.5 4.5
  9.65 1]
 [False False False False False False True False False 314 103 2 2.0 3.0
  8.21 0]
 [False False True False False False False False False 322 110 3 3.5 2.5
  8.67 1]]
